# Generated by Django 5.0.6 on 2024-08-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_category_alter_news_options_news_is_published_and_more'),
        ('News', '0002_news_is_published_alter_news_photo'),
    ]

    operations = [
    ]
